PUT http://localhost:8282/userRecipes/1
content-type: application/json

{
  "userId": 456,
  "strMeal": "Test Meal 1 - Update",
  "strCategory": "Test Category 1 - Update",
  "strArea": "Test Area 1 - Update",
  "strInstructions": "Test Instructions 1 - Update",
  "strMealThumb": "https://example.com/test.jpg",
  "strIngredient1": "Test Ingredient 1",
  "strIngredient2": "Test Ingredient 2",
  "strIngredient3": "Test Ingredient 3",
  "strIngredient4": "Test Ingredient 4",
  "strIngredient5": "Test Ingredient 5",
  "strIngredient6": "Test Ingredient 6",
  "strIngredient7": "Test Ingredient 7",
  "strIngredient8": "Test Ingredient 8",
  "strIngredient9": "Test Ingredient 9",
  "strIngredient10": "Test Ingredient 10",
  "strIngredient11": "Test Ingredient 11",
  "strIngredient12": "Test Ingredient 12",
  "strIngredient13": "Test Ingredient 13",
  "strIngredient14": "Test Ingredient 14",
  "strIngredient15": "Test Ingredient 15",
  "strIngredient16": "Test Ingredient 16",
  "strIngredient17": "Test Ingredient 17",
  "strIngredient18": "Test Ingredient 18",
  "strIngredient19": "Test Ingredient 19",
  "strIngredient20": "Test Ingredient 20",
  "strMeasure1": "Test Measure 1",
  "strMeasure2": "Test Measure 2",
  "strMeasure3": "Test Measure 3",
  "strMeasure4": "Test Measure 4",
  "strMeasure5": "Test Measure 5",
  "strMeasure6": "Test Measure 6",
  "strMeasure7": "Test Measure 7",
  "strMeasure8": "Test Measure 8",
  "strMeasure9": "Test Measure 9",
  "strMeasure10": "Test Measure 10",
  "strMeasure11": "Test Measure 11",
  "strMeasure12": "Test Measure 12",
  "strMeasure13": "Test Measure 13",
  "strMeasure14": "Test Measure 14",
  "strMeasure15": "Test Measure 15",
  "strMeasure16": "Test Measure 16",
  "strMeasure17": "Test Measure 17",
  "strMeasure18": "Test Measure 18",
  "strMeasure19": "Test Measure 19",
  "strMeasure20": "Test Measure 20"
}